import logging

LOG_MAIN_PATH = 'main.log'
LOG_MAIN_LEVEL = logging.INFO

VIDEO_DEVICE_ID = 0
VIDEO_WIDTH = 320
VIDEO_HEIGHT = 200
VIDEO_FILTER_COLOR = (255, 220, 60)
VIDEO_HUE_DELTA = 10
VIDEO_SATURATION_LOW = 0
VIDEO_SATURATION_HIGH = 255
VIDEO_VALUE_LOW = 0
VIDEO_VALUE_HIGH = 255